[[constraint]]
  name = "github.com/julienschmidt/httprouter"
  version = "=v1.1"

[[constraint]]
  name = "github.com/Unleash/unleash-client-go"
  revision = "be883ea1af714aff427d0668dbd4fc549d4f701c"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "=v1.0.0"

[[constraint]]
  name = "github.com/goadesign/goa"
  version = "=v1.3.1"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "=v1.1.4"

[[override]]
  name = "github.com/satori/go.uuid"
  revision = "36e9d2ebbde5e3f13ab2e25625fd453271d6522e"

